kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rhdh-k8s-plugin-ocm
rules:
- apiGroups:
    - cluster.open-cluster-management.io
  resources:
    - managedclusters
  verbs:
    - get
    - watch
    - list
- apiGroups:
    - internal.open-cluster-management.io
  resources:
    - managedclusterinfos
  verbs:
    - get
    - watch
    - list
