apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: example-statefulset
  labels:
    backstage.io/kubernetes-id: developer-hub
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  serviceName: example-service
  template:
    metadata:
      labels:
        app: example-app
        backstage.io/kubernetes-id: developer-hub
    spec:
      containers:
        - name: example-container
          image: nginxdemos/hello:plain-text
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    backstage.io/kubernetes-id: developer-hub
spec:
  selector:
    app: example-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
