apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: hello-world-pipeline-run
  labels:
    # this should match https://github.com/janus-qe/nationalparks-py/blob/master/catalog-info.yaml#L10
    backstage.io/kubernetes-id: developer-hub
spec:
  pipelineRef:
    name: hello-world-pipeline
