export const listLoadedPluginsResult = [
  {
    name: 'api-returned-some-plugin-one',
    version: '0.1.0',
    role: 'frontend-plugin',
    platform: 'web',
    internal: true,
    enabled: true,
  },
  {
    name: 'api-returned-some-plugin-two',
    version: '1.1.0',
    role: 'backend-plugin-module',
    platform: 'node',
    internal: false,
    enabled: true,
  },
  {
    name: 'api-returned-some-plugin-three',
    version: '0.1.2',
    role: 'backend-plugin',
    platform: 'node',
    internal: false,
    enabled: true,
  },
  {
    name: 'api-returned-some-plugin-four',
    version: '1.1.0',
    role: 'frontend-plugin',
    platform: 'web',
    internal: true,
    enabled: true,
  },
  {
    name: 'api-returned-some-plugin-five',
    version: '1.2.0',
    role: 'frontend-plugin',
    platform: 'web',
    internal: true,
    enabled: true,
  },
  {
    name: 'api-returned-some-plugin-six',
    version: '0.6.3',
    role: 'backend-plugin',
    platform: 'node',
    internal: true,
    enabled: true,
  },
];
