kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh

data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
    backend:
      auth:
        keys:
          - secret: temp
    integrations:
      # Plugin: GitHub
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}
      bitbucketServer:
        - host: bitbucket.com
          apiBaseUrl: temp
          username: temp
          password: temp
      gitlab:
        - host: gitlab.com
          token: temp
    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      environment: development
      providers:
        # Plugin: GitHub
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
        google:
          development:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}

    proxy:
      skipInvalidProxies: true
      # endpoints: {}
      endpoints:
        # Other Proxies
        # customize developer hub instance
        '/developer-hub':
          target: ${DH_TARGET_URL}
          changeOrigin: true
          # Change to "false" in case of using self hosted cluster with a self-signed certificate
          secure: false
        '/acr/api':
          target: 'https://rhdhqetest.azurecr.io/acr/v1/'
          changeOrigin: true
          headers:
            # If you use Bearer Token for authorization, please replace the 'Basic' with 'Bearer' in the following line.
            Authorization: '${ACR_SECRET}'
          # Change to "false" in case of using self hosted artifactory instance with a self-signed certificate
          secure: false

    catalog:
      import:
        entityFilename: catalog-info.yaml
        # pullRequestBranchName: rhdh-integration
        pullRequestBranchName: backstage-integration
      rules:
        - allow: [API, Component, Group, Location, Resource, System, Template]
      locations:
        - type: url
          target: https://github.com/janus-idp/backstage-showcase/blob/main/catalog-entities/all.yaml
        - type: url
          target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates.yaml
        - type: url
          target: https://github.com/janus-qe/acr-catalog/blob/main/catalog-info.yaml
        - type: url
          target: https://github.com/janus-qe/rhdh-test/blob/main/user.yml
          rules:
            - allow: [User]
        - type: url
          target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/acme-corp.yaml
          rules:
            - allow: [User, Group]


    dynatrace:
      baseUrl: temp
    argocd:
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: argoInstance1
              url: temp
              token: temp
            - name: argoInstance2
              url: temp
              token: temp
    permission:
      enabled: true
      rbac:
        policies-csv-file: './rbac/rbac-policy.csv'
        admin:
          users:
            - name: user:default/rhdh-qe 

