apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: development-keycloak
  labels:
    app: sso
  namespace: keycloak
spec:
  db:
    host: postgres-db
    passwordSecret:
      key: password
      name: keycloak-db-secret
    usernameSecret:
      key: username
      name: keycloak-db-secret
    vendor: postgres
  hostname:
    hostname: keycloak.apps-crc.testing
  http:
    httpEnabled: true
    httpPort: 8080
    tlsSecret: example-tls-secret
  instances: 1
