apiVersion: batch/v1
kind: CronJob
metadata:
  name: say-hello
  labels:
    backstage.io/kubernetes-id: developer-hub
spec:
  # Run Once an Hour
  schedule: "0  * * * *"
  jobTemplate:
    metadata:
      labels:
        backstage.io/kubernetes-id: developer-hub
    spec:
      template:
        metadata:
          labels:
            backstage.io/kubernetes-id: developer-hub
        spec:
          containers:
            - name: hello
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              command:
                - /bin/sh
                - -c
                - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
