apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: keycloak
  title: KeyCloak
  description: Keycloak is an open source software product to allow single sign-on with identity and access management aimed at modern applications and services. We use keycloack in this showcase.
  links:
    - url: https://www.keycloak.org/documentation
      title: Documentation
      icon: web
spec:
  type: identity-provider
  lifecycle: production
  owner: janus-authors
  system: janus-idp
