upstream:
  backstage:
    appConfig:
      auth:
        providers:
          oidc:
            production:
              metadataUrl: ${RHBK_METADATA_URL}
              clientId: ${RHBK_CLIENT_ID}
              clientSecret: ${RHBK_CLIENT_SECRET}
              prompt: auto 
              callbackUrl: ${RHBK_CALLBACK_URL}
      catalog:
        providers:
          keycloakOrg:
            default:
              baseUrl: ${RHBK_URL}
              loginRealm: ${AUTH_PROVIDERS_REALM_NAME}
              realm: ${AUTH_PROVIDERS_REALM_NAME}
              clientId: ${RHBK_CLIENT_ID}
              clientSecret: ${RHBK_CLIENT_SECRET}
              schedule:
                frequency: { minutes: 1 }
                timeout: { minutes: 1 }