kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha2
metadata:
  name: rhdh-rbac
spec:
  application:
    imagePullSecrets:
      - "rh-pull-secret"
    route:
      enabled: false
    image: 'quay.io/rhdh/rhdh-hub-rhel9:next'
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      secrets:
        - name: rhdh-secrets
    extraFiles:
      configMaps:
        - name: rbac-policy
      mountPath: /opt/app-root/src/rbac
