apiVersion: v1
kind: Secret
metadata:
  name: postgres-cred
type: Opaque
stringData:
  POSTGRES_PASSWORD: ""
  POSTGRES_PORT: ""
  POSTGRES_USER: ""
  POSTGRES_HOST: ""
  PGSSLMODE: "require"
  NODE_EXTRA_CA_CERTS: "/opt/app-root/src/postgres-crt.pem"
