apiVersion: rhdh.redhat.com/v1alpha2
kind: Backstage
metadata:
  name: rhdh-rbac
spec:
  deployment:
    patch:
      spec:
        template:
          spec:
            volumes:
              - $patch: replace
                name: dynamic-plugins-root
                persistentVolumeClaim:
                  claimName: dynamic-plugins-root