# Copyright 2023 The Janus IDP Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Multi-platform Docker Build and Push

on:
  workflow_call:
    inputs:
      registry:
        description: The registry to push to
        required: true
        type: string
      password:
        description: The password to use for the registry
        required: true
        type: string
      username:
        description: The username to use for the registry
        required: true
        type: string
      imageName:
        description: The name of the image to build
        required: true
        type: string
      imageTags:
        description: The tags to apply to the image
        required: true
        type: string
      imageLabels:
        description: The labels for the Docker image
        required: false
        type: string
      push:
        description: Whether to push the image
        required: true
        type: string
      platforms:
        description: "The platforms to build for (default: linux/amd64)"
        required: false
        default: linux/amd64
        type: string

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        if: ${{ inputs.push }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ inputs.username }}
          password: ${{ inputs.password }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.registry }}/${{ inputs.imageName }}
          tags: |
            ${{ inputs.imageTags }}
          labels: |
            ${{ inputs.imageLabels }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        id: build
        with:
          context: .
          file: docker/Dockerfile
          push: ${{ inputs.push }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.platforms }}
