name: Check Markdown links

on:
  pull_request:
    paths:
      - '**.md'
      - 'docs/**'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Check all markdown files in root
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/link-checker.config.json'

